# Question 1
Écrivez un programme Python pour convertir un tableau en une liste ordinaire avec les mêmes éléments.

Nous pouvons utiliser la fonction np.tolist() .

In [8]:
import numpy as np

tableau = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
liste = tableau.tolist()
print(liste)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


# Question 2
Écrivez un programme NumPy pour calculer la somme des éléments diagonaux d'un tableau donné.

Astuce : Il existe deux méthodes possibles pour résoudre ce problème : 

1-Manuellement (sans fonction directe). 
2-Utilisation de la fonction trace

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

sum_diagonal = np.trace(arr)
print("Somme des éléments diagonaux (fonction trace) :", sum_diagonal)

Somme des éléments diagonaux (fonction trace) : 15


# Question 3
Étant donné un tableau de votre choix, obtenez toutes les valeurs supérieures à X :

Si a = [[1,2],[3,5]] et x = 2 : alors 3 et 5 sont supérieurs à 2. 

In [7]:
import numpy as np

a = np.array([[1, 2],
              [3, 5]])
x = 2
indices = np.where(a > x)
result = a[indices]
print("Elements supérieurs à", x, "dans le tableau", a, "sont :", result)

Elements supérieurs à 2 dans le tableau [[1 2]
 [3 5]] sont : [3 5]


# Question 4
Étant donné deux tableaux, A et B ont la même forme. 

La tâche consiste à appliquer l'addition à la main : C est le nouveau tableau. 

In [6]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

n, m = A.shape

C = np.zeros((n, m))

for i in range(n):
    for j in range(m):
        C[i][j] = A[i][j] + B[i][j]

print("Tableau A :\n", A)
print("Tableau B :\n", B)
print("Tableau C (résultat de l'addition A + B):\n", C)


Tableau A :
 [[1 2 3]
 [4 5 6]]
Tableau B :
 [[ 7  8  9]
 [10 11 12]]
Tableau C (résultat de l'addition A + B):
 [[ 8. 10. 12.]
 [14. 16. 18.]]


# Question 5
Écrivez un programme NumPy pour soustraire la moyenne de chaque ligne d'une matrice donnée.

Astuce : utilisez la fonction moyenne

In [9]:
import numpy as np

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

mean_per_row = np.mean(M, axis=1)

M_centered = M - mean_per_row[:, np.newaxis]
print("Matrice d'origine :\n", M)
print("Matrice centrée :\n", M_centered)


Matrice d'origine :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrice centrée :
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
